# -*- coding: utf-8 -*-
"""QUIZ5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LofTI9MBVKsD5C6hrhrTirugaY3Cjigi
"""

import os
class Tablero:
    def __init__(self):
        self.casillas = {i: str(i) for i in range(1, 10)}
    def mostrar(self):
        os.system('cls' if os.name == 'nt' else 'clear')
        print("\n --- TIC TAC TOE POO ---")
        print(f"  {self.casillas[1]} | {self.casillas[2]} | {self.casillas[3]}")
        print(" ---+---+---")
        print(f"  {self.casillas[4]} | {self.casillas[5]} | {self.casillas[6]}")
        print(" ---+---+---")
        print(f"  {self.casillas[7]} | {self.casillas[8]} | {self.casillas[9]}")
        print(" -----------------------\n")
class Jugador:
    def __init__(self, nombre, simbolo):
        self.nombre = nombre
        self.simbolo = simbolo

    def elegir_jugada(self, opciones_validas):
        while True:
            try:
                movimiento = int(input(f"{self.nombre} ({self.simbolo}), elige casilla (1-9): "))
                if movimiento in opciones_validas:
                    return movimiento
                print("Esa casilla ya está ocupada o no existe.")
            except ValueError:
                print("Por favor, ingresa un número válido.")


jugador_ej = Jugador("Ana", "X")
print(f"Se han unido: {jugador_ej.nombre} con símbolo {jugador_ej.simbolo}")

class Juego:
    def __init__(self):
        self.tablero = Tablero()
        self.jugador1 = Jugador("Jugador 1", "X")
        self.jugador2 = Jugador("Jugador 2", "O")
        self.turno = self.jugador1
    def verificar_ganador(self):
        c = self.tablero.casillas
        combos = [(1,2,3), (4,5,6), (7,8,9), (1,4,7), (2,5,8), (3,6,9), (1,5,9), (3,5,7)]
        for a, b, d in combos:
            if c[a] == c[b] == c[d]:
                return True
        return False
    def jugar(self):
        casillas_libres = list(range(1, 10))
        while len(casillas_libres) > 0:
            self.tablero.mostrar()
            jugada = self.turno.elegir_jugada(casillas_libres)
            self.tablero.casillas[jugada] = self.turno.simbolo
            casillas_libres.remove(jugada)
            if self.verificar_ganador():
                self.tablero.mostrar()
                print(f"¡Felicidades {self.turno.nombre}! Has ganado.")
                return
            self.turno = self.jugador2 if self.turno == self.jugador1 else self.jugador1
        self.tablero.mostrar()
        print("¡Es un empate!")
partida = Juego()
partida.jugar()